### ISSUE TITLE
mbdyn-blender not showing in addons list

### ISSUE THREAD

**Issue by timgow** [zanoni-mbdyn/mbdyn-blender#1]
Hello,
I've downloaded the .zip file in Ubuntu 14.04 and performed file/properties/addons/'install from file' within Blender 2.75a.  I've refreshed the addons list but can't find 'mbdyn-blender' in the 'User' list and I've read through the 'All' list without recognising an addon entry to select.
I selected the mbdyn-blender-master.zip file 'install from file', I believe this is appropriate as other addons use the .zip file.
Please let me know what I should see when this addon is successfully installed.
Kind regards, Tim

**Comment by louisgag** [comment]
Hello Tim and Andrea,

On 21-Sep-2015 10:56 AM, timgow wrote:

> Hello,
> I've downloaded the .zip file in Ubuntu 14.04 and performed 
> file/properties/addons/'install from file' within Blender 2.75a. I've 
> refreshed the addons list but can't find 'mbdyn-blender' in the 'User' 
> list and I've read through the 'All' list without recognising an addon 
> entry to select
> 
> .
> I selected the mbdyn-blender-master.zip file 'install from file', I 
> believe this is appropriate as other addons use the .zip file.
> 
> your procedure seems fine
> 
> Please let me know what I should see when this addon is successfully 
> installed.
> 
> I tested on my computer and have the same issue
> 
> Kind regards, Tim
> 
> Regards,
> -Louis
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/zanoni-mbdyn/mbdyn-blender/issues/1.

## 

Louis Gagnon, Ph.D.
Dipartimento di Scienze e Tecnologie Aerospaziali
Politecnico di Milano

**Comment by zanoni-mbdyn** [comment]
Hello Tim and Louis, 

I'm sorry, the repository needed some cleaning and I forgot of that lately. 

Now it should be OK and I've updated the README file as to point out the correct installation procedure: 
you should extract the .zip file and then install the add-on by using the "Install from file" button in the User Preferences tab, pointing to the MBDynImport.py file.

The add-on will show under the "Animation" tab in the list. 

Let me know if everything is okay now. 
Thanks for the feedback.
Andrea

**Comment by timgow** [comment]
Andrea,
Thank you for the installation procedure; I now have the 'MBDyn Motion Path' tab.  I've imported the joint_break.mov example file, I get the "MBDyn elements imported successfully" message, but I don't see any elements on-screen.  The terminal output for blender is as follows:

Reading from file /home/tim/Downloads/mbdyn-blender-master/test/joint_break.mov
File /home/tim/Downloads/mbdyn-blender-master/test/joint_break.mov has 2004 rows
Reading node list from file:  /home/tim/Downloads/mbdyn-blender-master/test/joint_break.mov
create_nodes_dict(): Reading node labels from file:  /home/tim/Downloads/mbdyn-blender-master/test/joint_break.lab
create_nodes_dict(): WARNING - String label of node 0 changed from 'Node_0' to node_ground
create_nodes_dict(): WARNING - String label of node 1 changed from 'Node_1' to node_body1
Nodes dictionary:
0   node_ground
1   node_body1
parse_log_file(): Trying to read elements from file: /home/tim/Downloads/mbdyn-blender-master/test/joint_break.log
parse_log_file(): Found output frequency element.
Element type output frequency not implemented yet. Skipping
parse_log_file(): Found structural node element.
Element type structural node not implemented yet. Skipping
parse_log_file(): Found structural node element.
Element type structural node not implemented yet. Skipping
parse_log_file(): Found body element.
Element type body not implemented yet. Skipping
parse_log_file(): Found clamp element.
Element type clamp not implemented yet. Skipping
parse_log_file(): Found deformabledisplacementjoint element.
Element type deformabledisplacementjoint not implemented yet. Skipping
parse_log_file(): Found totaljoint element.
Element type totaljoint not implemented yet. Skipping
parse_log_file(): Found struct node dofs element.
Element type struct node dofs not implemented yet. Skipping
parse_log_file(): Found struct node eqs element.
Element type struct node eqs not implemented yet. Skipping
parse_log_file(): row does not contain an element definition. Skipping...
parse_log_file(): row does not contain an element definition. Skipping...
parse_log_file(): row does not contain an element definition. Skipping...
parse_log_file(): row does not contain an element definition. Skipping...
parse_log_file(): row does not contain an element definition. Skipping...
parse_log_file(): row does not contain an element definition. Skipping...
parse_log_file(): Found struct node labels element.
Element type struct node labels not implemented yet. Skipping
parse_log_file(): row does not contain an element definition. Skipping...
parse_log_file(): row does not contain an element definition. Skipping...
Info: MBDyn elements imported successfully

Please let me know whether I'm missing a step that allows me to visualise the example MBDyn results or whether there are no elements to see due to none being imported.

Kind regards,
Tim

---

On Mon, 21/9/15, zanoni-mbdyn notifications@github.com wrote:

 Subject: Re: [mbdyn-blender] mbdyn-blender not showing in addons list (#1)
 To: "zanoni-mbdyn/mbdyn-blender" mbdyn-blender@noreply.github.com
 Cc: "timgow" tim@gowingeng.co.uk
 Date: Monday, 21 September, 2015, 10:39

 Hello Tim and Louis, 

 I'm sorry, the repository needed some cleaning and I
 forgot of that lately. 

 Now it should be OK and I've updated the README file
 as to point out the correct installation procedure: 

 you should extract the .zip file and then install the add-on
 by using the "Install from file" button in the
 User Preferences tab, pointing to the MBDynImport.py
 file.

 The add-on will show under the "Animation" tab
 in the list. 

 Let me know if everything is okay now. 

 Thanks for the feedback.

 Andrea

 —
 Reply to this email directly or view
 it on GitHub.

**Comment by zanoni-mbdyn** [comment]
Hi Tim,

the import elements button is largely a placeholder right now: it can load
and display correctly only rod elements. If you tell me which elements
you'll like to visualize, I'll see if I can find the time to implement
their support in the next few days and let you test it and give feedback.

Please notice that the elements that the add-on finds in the .log file are
listed under the 'Scene' tab in the Properties Panel of Blender, and that
only supported elements are listed.

Cheers,
Andrea

2015-09-21 12:57 GMT+02:00 timgow notifications@github.com:

> Andrea,
> Thank you for the installation procedure; I now have the 'MBDyn Motion
> Path' tab. I've imported the joint_break.mov example file, I get the "MBDyn
> elements imported successfully" message, but I don't see any elements
> on-screen. The terminal output for blender is as follows:
> 
> Reading from file
> /home/tim/Downloads/mbdyn-blender-master/test/joint_break.mov
> File /home/tim/Downloads/mbdyn-blender-master/test/joint_break.mov has
> 2004 rows
> Reading node list from file:
> /home/tim/Downloads/mbdyn-blender-master/test/joint_break.mov
> create_nodes_dict(): Reading node labels from file:
> /home/tim/Downloads/mbdyn-blender-master/test/joint_break.lab
> create_nodes_dict(): WARNING - String label of node 0 changed from
> 'Node_0' to node_ground
> create_nodes_dict(): WARNING - String label of node 1 changed from
> 'Node_1' to node_body1
> Nodes dictionary:
> 0 node_ground
> 1 node_body1
> parse_log_file(): Trying to read elements from file:
> /home/tim/Downloads/mbdyn-blender-master/test/joint_break.log
> parse_log_file(): Found output frequency element.
> Element type output frequency not implemented yet. Skipping
> parse_log_file(): Found structural node element.
> Element type structural node not implemented yet. Skipping
> parse_log_file(): Found structural node element.
> Element type structural node not implemented yet. Skipping
> parse_log_file(): Found body element.
> Element type body not implemented yet. Skipping
> parse_log_file(): Found clamp element.
> Element type clamp not implemented yet. Skipping
> parse_log_file(): Found deformabledisplacementjoint element.
> Element type deformabledisplacementjoint not implemented yet. Skipping
> parse_log_file(): Found totaljoint element.
> Element type totaljoint not implemented yet. Skipping
> parse_log_file(): Found struct node dofs element.
> Element type struct node dofs not implemented yet. Skipping
> parse_log_file(): Found struct node eqs element.
> Element type struct node eqs not implemented yet. Skipping
> parse_log_file(): row does not contain an element definition. Skipping...
> parse_log_file(): row does not contain an element definition. Skipping...
> parse_log_file(): row does not contain an element definition. Skipping...
> parse_log_file(): row does not contain an element definition. Skipping...
> parse_log_file(): row does not contain an element definition. Skipping...
> parse_log_file(): row does not contain an element definition. Skipping...
> parse_log_file(): Found struct node labels element.
> Element type struct node labels not implemented yet. Skipping
> parse_log_file(): row does not contain an element definition. Skipping...
> parse_log_file(): row does not contain an element definition. Skipping...
> Info: MBDyn elements imported successfully
> 
> Please let me know whether I'm missing a step that allows me to visualise
> the example MBDyn results or whether there are no elements to see due to
> none being imported.
> 
> Kind regards,
> Tim
> 
> ---
>

**Comment by timgow** [comment]
Andrea,
I'll see if I can work with rod elements for the time being, I'll let you know if can't progress without other elements.
Many thanks for your help.
Tim

---

On Mon, 21/9/15, zanoni-mbdyn notifications@github.com wrote:

 Subject: Re: [mbdyn-blender] mbdyn-blender not showing in addons list (#1)
 To: "zanoni-mbdyn/mbdyn-blender" mbdyn-blender@noreply.github.com
 Cc: "timgow" tim@gowingeng.co.uk
 Date: Monday, 21 September, 2015, 14:18

 Hi Tim,

 the import elements button is largely a placeholder right
 now: it can load

 and display correctly only rod elements. If you tell me
 which elements

 you'll like to visualize, I'll see if I can find the
 time to implement

 their support in the next few days and let you test it and
 give feedback.

 Please notice that the elements that the add-on finds in the
 .log file are

 listed under the 'Scene' tab in the Properties Panel
 of Blender, and that

 only supported elements are listed.

 Cheers,

 Andrea

 2015-09-21 12:57 GMT+02:00 timgow
 notifications@github.com:

> Andrea,
> 
> Thank you for the installation procedure; I now have
>  the 'MBDyn Motion
> 
> Path' tab. I've imported the joint_break.mov
>  example file, I get the "MBDyn
> 
> elements imported successfully" message, but I
>  don't see any elements
> 
> on-screen. The terminal output for blender is as
>  follows:
> 
> Reading from file
> 
>  /home/tim/Downloads/mbdyn-blender-master/test/joint_break.mov
> 
> File
>  /home/tim/Downloads/mbdyn-blender-master/test/joint_break.mov
>  has
> 
> 2004 rows
> 
> Reading node list from file:
> 
>  /home/tim/Downloads/mbdyn-blender-master/test/joint_break.mov
> 
> create_nodes_dict(): Reading node labels from file:
> 
>  /home/tim/Downloads/mbdyn-blender-master/test/joint_break.lab
> 
> create_nodes_dict(): WARNING - String label of node 0
>  changed from
> 
> 'Node_0' to node_ground
> 
> create_nodes_dict(): WARNING - String label of node 1
>  changed from
> 
> 'Node_1' to node_body1
> 
> Nodes dictionary:
> 
> 0 node_ground
> 
> 1 node_body1
> 
> parse_log_file(): Trying to read elements from file:
> 
>  /home/tim/Downloads/mbdyn-blender-master/test/joint_break.log
> 
> parse_log_file(): Found output frequency element.
> 
> Element type output frequency not implemented yet.
>  Skipping
> 
> parse_log_file(): Found structural node element.
> 
> Element type structural node not implemented yet.
>  Skipping
> 
> parse_log_file(): Found structural node element.
> 
> Element type structural node not implemented yet.
>  Skipping
> 
> parse_log_file(): Found body element.
> 
> Element type body not implemented yet. Skipping
> 
> parse_log_file(): Found clamp element.
> 
> Element type clamp not implemented yet. Skipping
> 
> parse_log_file(): Found deformabledisplacementjoint
>  element.
> 
> Element type deformabledisplacementjoint not
>  implemented yet. Skipping
> 
> parse_log_file(): Found totaljoint element.
> 
> Element type totaljoint not implemented yet. Skipping
> 
> parse_log_file(): Found struct node dofs element.
> 
> Element type struct node dofs not implemented yet.
>  Skipping
> 
> parse_log_file(): Found struct node eqs element.
> 
> Element type struct node eqs not implemented yet.
>  Skipping
> 
> parse_log_file(): row does not contain an element
>  definition. Skipping...
> 
> parse_log_file(): row does not contain an element
>  definition. Skipping...
> 
> parse_log_file(): row does not contain an element
>  definition. Skipping...
> 
> parse_log_file(): row does not contain an element
>  definition. Skipping...
> 
> parse_log_file(): row does not contain an element
>  definition. Skipping...
> 
> parse_log_file(): row does not contain an element
>  definition. Skipping...
> 
> parse_log_file(): Found struct node labels element.
> 
> Element type struct node labels not implemented yet.
>  Skipping
> 
> parse_log_file(): row does not contain an element
>  definition. Skipping...
> 
> parse_log_file(): row does not contain an element
>  definition. Skipping...
> 
> Info: MBDyn elements imported successfully
> 
> Please let me know whether I'm missing a step that
>  allows me to visualise
> 
> the example MBDyn results or whether there are no
>  elements to see due to
> 
> none being imported.
> 
> Kind regards,
> 
> Tim
> 
> ---
> 
> On Mon, 21/9/15, zanoni-mbdyn
>  notifications@github.com wrote:
> 
> Subject: Re: [mbdyn-blender] mbdyn-blender not showing
>  in addons list (#1)
> 
> To: "zanoni-mbdyn/mbdyn-blender"
>  mbdyn-blender@noreply.github.com
> 
> Cc: "timgow" tim@gowingeng.co.uk
> 
> Date: Monday, 21 September, 2015, 10:39
> 
> Hello Tim and Louis,
> 
> I'm sorry, the repository needed some cleaning and
>  I
> 
> forgot of that lately.
> 
> Now it should be OK and I've updated the README
>  file
> 
> as to point out the correct installation procedure:
> 
> you should extract the .zip file and then install the
>  add-on
> 
> by using the "Install from file" button in
>  the
> 
> User Preferences tab, pointing to the MBDynImport.py
> 
> file.
> 
> The add-on will show under the "Animation"
>  tab
> 
> in the list.
> 
> Let me know if everything is okay now.
> 
> Thanks for the feedback.
> 
> Andrea
> 
> —
> 
> Reply to this email directly or view
> 
> it on GitHub.
> 
> —
> 
> Reply to this email directly or view it on GitHub
> 
>  https://github.com/zanoni-mbdyn/mbdyn-blender/issues/1#issuecomment-141940949
> 
> .

 —
 Reply to this email directly or view
 it on GitHub.
